### PR TITLE
Add ability to track directories

### PR DESCRIPTION
**Pull request by sowmiyamuthuraman**
Fixes https://github.com/thetinygoat/dotfm/issues/1

### CODE REVIEW

**Comment by thetinygoat** [comment]
You should also update the list function to indicate whether the listed item is file or directory

**Comment by sowmiyamuthuraman** [comment]
> You should also update the list function to indicate whether the listed item is file or directory

Whats the format you suggest to indicate the item is a file or directory?

**Comment by thetinygoat** [comment]
I think linux format works fine

**Comment by thetinygoat** [comment]
Merged, thanks

**Pull request merged**
